# Generated by Django 5.0.2 on 2024-03-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_comment_comment_text_alter_comment_user_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_text',
            new_name='text',
        ),
        migrations.AddField(
            model_name='comment',
            name='user_email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
