# Generated by Django 5.0.2 on 2024-03-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_comment_text_comment_text_comment_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_email',
            field=models.EmailField(max_length=254),
        ),
    ]
